[package]
name = "difftoml"
version = "0.2.0"
authors = ["Ole-Johan Skrede <skrede@protonmail.com>"]
edition = "2018"

[dependencies]
anyhow = "1.0"
clap = "2.33"
colored = "2.0"
itertools = "0.10"
toml = "0.5"
