ip = '127.0.0.1'
sample_from_grid = true

[keys]
github = 'xxxxxxxxxxxxxxxxx'
travis = 'yyyyyyyyyyyyyyyyy'

[input]
sample_from_grid = true
train_std = [ 43.21194, 51.17222, 34.87386,]
input_data_format = "hybrid_pretiled"
hue_delta = 0.05
