name = "first"
version = "0.1.0"
int_value = 123
float_value = 1.23

[field0]
name = "a"
values = [0.12, 3.45, 6.78]

[field1]
name = "b"
values = [1.23, 4.56, 7.89]

[field2]
name = "c"
values = [2.34, 5.67, 8.90]
